trigger:
  branches:
    include: [ '*' ]
    exclude: [ 'refs/tags/*' ]

jobs:

- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:

  - powershell: .\build.ps1 --target=Test --test-run-name=Windows
    displayName: Build, test, and publish results

  - powershell: .\build.ps1 --target=Package --artifact-dir='$(Build.ArtifactStagingDirectory)'
    displayName: Package

  - task: PublishBuildArtifacts@1
    displayName: Save package artifacts
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: Package

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: ./build.sh --target=Test --test-run-name=Linux --configuration=Release
    displayName: Build, test, and publish results

- job: macOS
  pool:
    vmImage: macOS-10.13
  steps:
  - bash: ./build.sh --target=Test --test-run-name=macOS --configuration=Release
    displayName: Build, test, and publish results
