trigger:
  branches:
    include: [ '*' ]
    exclude: [ 'refs/tags/*' ]

jobs:

- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:

  - powershell: .\build.ps1 --target=Test
    displayName: Build and test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**\TestResult.xml'
      testRunTitle: Windows
    condition: succeededOrFailed()

  - powershell: .\build.ps1 --target=Package --artifact-dir='$(Build.ArtifactStagingDirectory)'
    displayName: Package

  - task: PublishBuildArtifacts@1
    displayName: Save package artifacts
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: Package

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:

  - bash: ./build.sh --target=Test --configuration=Release
    displayName: Build and test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**\TestResult.xml'
      testRunTitle: Linux
    condition: succeededOrFailed()

- job: macOS
  pool:
    vmImage: macOS-10.13
  steps:

  - bash: ./build.sh --target=Test --configuration=Release
    displayName: Build and test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**\TestResult.xml'
      testRunTitle: macOS
    condition: succeededOrFailed()
